artifacts_root: artifacts

# PDF Processing
model_load:
  root_dir: artifacts/model_load
  model_names:
    - "TheBloke/Mistral-7B-Instruct-v0.1-GGUF mistral-7b-instruct-v0.1.Q3_K_M.gguf"
    - "TheBloke/Mistral-7B-Instruct-v0.1-GGUF mistral-7b-instruct-v0.1.Q5_K_M.gguf"
  model_directory: artifacts/model_load/models

# URL Content Processing
url_processing:
  root_dir: artifacts/url_processing
  processed_directory: artifacts/url_processing/processed
  temp_directory: artifacts/url_processing/temp

# Data Cleaning
data_cleaning:
  root_dir: artifacts/data_cleaning
  cleaned_data_directory: artifacts/data_cleaning/cleaned

# Vectorization and Database Management
vectorization:
  root_dir: artifacts/vectorization
  embedding_model: "text-embedding-ada-002"
  vector_db_directory: artifacts/vectorization/vectordb

database_management:
  root_dir: artifacts/vectorization/vectordb
  db_path: artifacts/vectorization/vectordb/db.sqlite3

# OpenAI API Integration
openai_integration:
  root_dir: artifacts/openai_integration
  default_model: "gpt-4-turbo-preview"
  temperature: 0.0

# Chat History Management
chat_history:
  root_dir: artifacts/chat_history
  max_entries: 5
  storage_file: artifacts/chat_history/{session_id}.csv

# Application Configuration
application:
  streamlit_app:
    root_dir: artifacts/ui
    port: 8501

  api_service:
    root_dir: artifacts/api_service
    port: 5000

# Experimental Settings
experimental:
  root_dir: artifacts/experimental
  trials_notebook: artifacts/experimental/trials.ipynb
